Added partial support for meta.com
mozilla/cookie-banner-rules-list pull request #478
Opened 2024-03-11 23:10 UTC by Greg-21

In this pull request, I modified the existing rule for the standard cookie banner used by Meta on a large part of their websites to add partial support for meta.com. In practice, only about.meta.com seems to be the beneficiary of this change, but it is still better than no support at all, isn't it?

Resolves #476

2024-03-22 17:55 UTC, abhishekmadan30 requested changes
I think it would better to not have this there, if it does not work for the base domain

2024-03-23 16:05 UTC, Greg-21 commented
I would love to have support for the Meta home page, but adding support for the more modern banner seems to be much more difficult than for the one for which I propose to add support in this PR.

Maybe with some help I could figure it out ¯\_(ツ)_/¯

2024-03-23 16:15 UTC, Greg-21 commented
I would love to have support for the Meta home page, but adding support for the more modern banner seems to be much more difficult than for the one for which I propose to add support in this PR.

Maybe with some help I could figure it out ¯\\\_(ツ)_/¯

2024-04-24 19:45 UTC, Greg-21 commented
Superseded by #505.

2024-04-24 19:45 UTC, closed without merging